version: '3.5'

# remember to use the postgres container name in pgadmin 'host' option
services:
  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres-compose-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    networks:
      - postgres-compose-network
    depends_on:
      - db

volumes:
  postgres:
  pgadmin:

networks:
  postgres-compose-network:
    driver: bridge
